import bcrypt from 'bcryptjs';
import pool from '../config/db.js';

/**
 * @typedef {Object} UserRegistrationPayload
 * @property {string} username - Desired unique username.
 * @property {string} email - Unique email address of the user.
 * @property {string} password - Raw, unhashed user password.
 */

/**
 * @typedef {Object} SanitizedUser
 * @property {number|string} id - Unique identifier generated by the database.
 * @property {string} username - User's unique handle.
 * @property {string} email - User's registered email address.
 * @property {string|Date} created_at - Timestamp of account creation.
 */

/**
 * Handles the registration of a new user account.
 * 
 * Validates unique constraints (username/email), hashes sensitive credentials using
 * a cryptographic salt, persists the entity within PostgreSQL via parameterized queries,
 * and yields sanitized user metadata omitting sensitive authentication details.
 *
 * @async
 * @function registerUser
 * @param {import('express').Request<{}, {}, UserRegistrationPayload>} req - Express request object containing parsed registration credentials.
 * @param {import('express').Response} res - Express response object used to transmit HTTP status and response payload.
 * @returns {Promise<import('express').Response>} Resolves with an HTTP 201 Created and the persisted sanitized user entity,
 *                                                an HTTP 400 Bad Request if collision is detected,
 *                                                or an HTTP 500 Internal Server Error upon operational/system failures.
 */
export const registerUser = async (req, res) => {
  const { username, email, password } = req.body;

  try {
    /**
     * Verify unique constraints against database.
     * Prevents duplicate username or email collisions prior to write operations.
     */
    const userExists = await pool.query(
      'SELECT id FROM users WHERE email = $1 OR username = $2',
      [email, username]
    );

    if (userExists.rows.length > 0) {
      return res.status(400).json({ error: 'Username or email already in use.' });
    }

    /**
     * Password Cryptography
     * Generate an adaptive crypt salt factor (cost 10) and securely hash the raw password.
     */
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(password, salt);

    /**
     * Persist record using parameterized queries to prevent SQL Injection attacks.
     * Explicitly projects non-sensitive fields to safeguard the password hash from leakage.
     */
    const newUser = await pool.query(
      `INSERT INTO users (username, email, password)
      VALUES($1, $2, $3) 
      RETURNING id, username, email, created_at`,
      [username, email, hashedPassword]
    );

    return res.status(201).json({
      message: 'User registered successfully',
      user: newUser.rows[0]
    });
  } catch (err) {
    console.error(`[Register User Error] ${err.message}`);
    return res.status(500).json({
      error: 'Internal server error',
      message: err.message || 'An unexpected error occurred'
    });
  }
};
